car/urls.py
from django.urls import include, path

from . import views

app_name = "car"

urlpatterns = [
    path("", views.CarListView.as_view(), name="list"),
    path("create/", views.CarCreateView.as_view(), name="create"),
    path("<int:pk>/", views.CarDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", views.CarUpdateView.as_view(), name="update"),
    path(
        "booking/",
        include(
            [
                path("", views.CarBookingListView.as_view(), name="booking"),
                path(
                    "create/<int:pk>/",
                    views.CarBookingCreateView.as_view(),
                    name="booking-create",
                ),
                path(
                    "detail/<int:pk>/",
                    views.CarBookingDetailView.as_view(),
                    name="booking-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarBookingUpdateView.as_view(),
                    name="booking-update",
                ),
                path("wait/", views.WaitApproveListView.as_view(), name="wait_approve"),
                path(
                    "return/<int:pk>/",
                    views.ReturnCar,
                    name="return-car",
                ),
                path(
                    "approve/<int:pk>/",
                    views.car_booking_approve,
                    name="booking-approve",
                ),
                path(
                    "reject/<int:pk>/",
                    views.car_booking_reject,
                    name="booking-reject",
                ),
                path("use/<int:pk>/", views.UseCar, name="use-car"),
            ]
        ),
    ),
    path(
        "fix/",
        include(
            [
                path("", views.CarRequestFixListView.as_view(), name="fix"),
                path(
                    "create/<int:pk>/",
                    views.CarFixCreateView.as_view(),
                    name="fix-create",
                ),
                path(
                    "<int:pk>/",
                    views.CarRequestFixDetailView.as_view(),
                    name="fix-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarFixUpdateView.as_view(),
                    name="fix-update",
                ),
                path(
                    "after-fix/<int:pk>/",
                    views.CarAfterFixView,
                    name="after-fix",
                ),
                path(
                    "my-fix/",
                    views.ResponsibleListView.as_view(),
                    name="my-fix",
                ),
                path("refuel/<int:pk>/", views.RefuelCar, name="refuel"),
            ]
        ),
    ),
    # path('return/<int:pk>/', views.ReturnCar.as_view(), name='return-car'),
]

config/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : urls.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Sep, 22 2022, 15:06 265
# Last Modified Date: Mon Jun, 24 2024, 16:01 176
# Last Modified By  : lu5her <lu5her@mail>
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# for test template
from django.views.generic import TemplateView

from account import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("test/", TemplateView.as_view(template_name="test.html"), name="test"),
    # url for under development page
    path(
        "develop/", TemplateView.as_view(template_name="under_dev.html"), name="develop"
    ),
    path("", views.HomeView.as_view(), name="home"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    # internal url
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("announce/", include("announce.urls")),
    path("document/", include("document.urls")),
    path("journal/", include("journal.urls")),
    path("assign/", include("assign.urls")),
    path("car/", include("car.urls")),
    path("asset/", include("asset.urls")),
    path("inform/", include("inform.urls")),
    path("repair/", include("repair.urls")),
    path("parcel/", include("parcel.urls")),
    path("cart/", include("cart.urls")),
    path(
        "operation/",
        include(
            "operation.urls",
        ),
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

parcel/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : urls.py
# Author            : lu5her <lu5her@mail>
# Date              : Sat Jun, 15 2024, 21:48 167
# Last Modified Date: Thu Jun, 20 2024, 17:25 172
# Last Modified By  : lu5her <lu5her@mail>
# -----
from django.urls import include, path

from . import views

app_name = "parcel"

urlpatterns = [
    path("", views.ParcelHomeView.as_view(), name="home"),
    path("select_stock/", views.SelectStockView.as_view(), name="select_stock"),
    path("select_item/<int:pk>/", views.SelecItemView.as_view(), name="select_item"),
    # path('test_create_bill/', views.test_create_bill, name='test_create_bill'),
    path("parcel_list/", views.ParcelListView.as_view(), name="parcel_list"),
    path(
        "bill/",
        include(
            [
                path("list/", views.BillListView.as_view(), name="bill_list"),
                path(
                    "detail/<int:pk>/",
                    views.BillDetailView.as_view(),
                    name="bill_detail",
                ),
                path("create/", views.BillCreateView.as_view(), name="bill_create"),
                path("save_draft/<int:pk>/", views.save_draft, name="save_draft"),
                path("request_bill/<int:pk>/", views.request_bill, name="request_bill"),
            ]
        ),
    ),
    # user after request_bill
    path(
        "user/",
        include(
            [
                path(
                    "item_on_hand_list/",
                    views.ItemOnHandListView.as_view(),
                    name="item_on_hand_list",
                ),
                path(
                    "recieve_item/<int:pk>/",
                    views.RecieveItemsView.as_view(),
                    name="recieve_item",
                ),
                path(
                    "parcel_detail/<int:pk>/",
                    views.ParcelDetailView.as_view(),
                    name="parcel_detail",
                ),
                path("set_item/", views.SetItemLocationView.as_view(), name="set_item"),
                path(
                    "replace_item/",
                    views.ReplaceItemLocationView.as_view(),
                    name="replace_item",
                ),
                path(
                    "return_parcel/create",
                    views.ReturnParcelCreateView.as_view(),
                    name="return_parcel_create",
                ),
                path(
                    "draft_list/",
                    views.ParcelReturnDraftListView.as_view(),
                    name="draft_list",
                ),
                path(
                    "location_list/",
                    views.LocationListView.as_view(),
                    name="location_list",
                ),
                path(
                    "item_on_location/<int:pk>/",
                    views.ItemOnLocationView.as_view(),
                    name="item_on_location",
                ),
                path(
                    "remove_item/", views.RemoveItemView.as_view(), name="remove_item"
                ),
            ]
        ),
    ),
    # return parcel urls
    path(
        "return/",
        include(
            [
                path(
                    "parcel/list/",
                    views.ParcelReturnListView.as_view(),
                    name="return_parcel_list",
                ),
                path(
                    "<int:pk>/",
                    views.ReturnParcelDetailView.as_view(),
                    name="return_parcel_detail",
                ),
                path(
                    "save_return_draft/<int:pk>/",
                    views.save_return_draft,
                    name="save_return_draft",
                ),
                path("return_item/<int:pk>/", views.return_item, name="return_item"),
            ]
        ),
    ),
    # manager ulrs
    path(
        "manager/",
        include(
            [
                path("list/", views.BillManagerListView.as_view(), name="manager_list"),
                path(
                    "wait_approve/",
                    views.BillWaitApproveListView.as_view(),
                    name="manager_wait_approve",
                ),
                path(
                    "wait_paid/",
                    views.BillWaitPaidListView.as_view(),
                    name="manager_wait_paid",
                ),
                path(
                    "all_bills/",
                    views.ManagerAllBillListView.as_view(),
                    name="manager_all_bills",
                ),
                path(
                    "request_approve/<int:pk>/",
                    views.request_approve,
                    name="request_approve",
                ),
                path(
                    "set_serial_item/<int:pk>/",
                    views.set_serial_item,
                    name="set_serial_item",
                ),
                path(
                    "paid_item/<int:pk>/",
                    views.PaidItemView.as_view(),
                    name="paid_item",
                ),
                path(
                    "parcel/return/list/",
                    views.ReturnManagerListView.as_view(),
                    name="return_manager_list",
                ),
                path(
                    "parcel/checker_confirm_return/<int:pk>/",
                    views.checker_confirm_return,
                    name="checker_confirm_return",
                ),
            ]
        ),
    ),
    # command urls
    # path('approve_request/<int:pk>/', views.approve_request, name='approve_request'),
    path(
        "command/",
        include(
            [
                path("approve_bill/<int:pk>/", views.approve_bill, name="approve_bill"),
                path(
                    "wait_approve/list/",
                    views.CommandWaitApproveListView.as_view(),
                    name="command_wait_approve",
                ),
                path(
                    "return_wait_approve/list/",
                    views.ReturnCommandListView.as_view(),
                    name="return_wait_approve",
                ),
                path("reject_bill/<int:pk>/", views.reject_bill, name="reject_bill"),
                path("bill_to_pdf/<int:pk>/", views.bill_to_pdf, name="bill_to_pdf"),
                path(
                    "return_parcel/pdf/<int:pk>/",
                    views.return_pdf,
                    name="return_pdf",
                ),
                path(
                    "wait_approve/list/",
                    views.ReturnCommandListView.as_view(),
                    name="return_command_list",
                ),
                path(
                    "approve_return/<int:pk>/",
                    views.return_approve,
                    name="return_approve",
                ),
                path(
                    "control_return/<int:pk>/",
                    views.return_controler,
                    name="return_controler",
                ),
                path(
                    "return_done/<int:pk>/",
                    views.return_done,
                    name="return_done",
                ),
            ]
        ),
    ),
]

parcel/forms.py
from account.models import Department, Profile
from django import forms

from .models import (
    ParcelReturnDetail,
    RequestBillDetail,
)


class SelectStockForm(forms.Form):
    """
    SelectStockForm for create new SelectStock

    Attributes:
        department:
        queryset:
    """

    department = forms.ModelChoiceField(queryset=None, required=True)

    class Meta:
        fields = ("department",)
        labels = {"department": "เลือกคลัง"}
        widgets = {
            "department": forms.Select(attrs={"class": "form-select"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["department"].queryset = Department.objects.filter(
            name__startswith="คลัง"
        )


# class BillCreateForm(forms.ModelForm):
#     class Meta:
#         model = RequestBill
#         fields = (
#             'receiver',
#         )
#         widgets = {
#             'receiver': forms.Select(attrs={'class': 'form-select'}),
#         }


class RequestBillDetailForm(forms.ModelForm):
    """
    RequestBillDetailForm for create new RequestBillDetail

    Attributes:
        queryset:
        queryset:
    """

    class Meta:
        model = RequestBillDetail
        fields = (
            "request_case",
            "item_type",
            "item_control",
            "money_type",
            "job_no",
            "request_reference",
            "receiver",
            "bill",
        )
        widgets = {
            "request_case": forms.Select(attrs={"class": "form-select"}),
            "item_type": forms.TextInput(attrs={"class": "form-control"}),
            "item_control": forms.TextInput(attrs={"class": "form-control"}),
            "money_type": forms.TextInput(attrs={"class": "form-control"}),
            "job_no": forms.TextInput(attrs={"class": "form-control"}),
            "request_reference": forms.TextInput(attrs={"class": "form-control"}),
            "receiver": forms.Select(attrs={"class": "form-select"}),
        }
        labels = {
            "request_case": "เบิกในกรณี",
            "item_type": "ประเภท สป.",
            "item_control": "สายงานควบคุม",
            "money_type": "ประเภทเงิน",
            "job_no": "เลขที่งาน",
            "request_reference": "เอกสารอ้างอิง",
            "receiver": "ผู้รับแทน",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["request_case"].queryset = RequestBillDetail.RequestCase
        self.fields["receiver"].queryset = Profile.objects.all()


class ReturnBillDetailForm(forms.ModelForm):
    """
    ReturnBillDetailForm for create new ReturnBillDetail
    """

    class Meta:
        model = ParcelReturnDetail
        fields = (
            "return_case",
            "item_type",
            "item_control",
            "money_type",
            "job_no",
        )
        widgets = {
            "return_case": forms.Select(attrs={"class": "form-select"}),
            "item_type": forms.TextInput(attrs={"class": "form-control"}),
            "item_control": forms.TextInput(attrs={"class": "form-control"}),
            "money_type": forms.TextInput(attrs={"class": "form-control"}),
            "job_no": forms.TextInput(attrs={"class": "form-control"}),
        }
        labels = {
            "return_case": "เหตุที่ส่งคืน",
            "item_type": "ประเภท สป.",
            "item_control": "สายงานควบคุม",
            "money_type": "ประเภทเงิน",
            "job_no": "เลขที่งาน",
        }

parcel/templates/parcel/components/command_card.html
{% load tags %}
<div class="col-xxl-4 col-md-6">
  <div class="card info-card bg-card">
    <a href="{% url 'parcel:command_wait_approve' %}">
      <div class="card-body">
        <h5 class="card-title">รายการใบเบิก <span>| ขออนุมัติ</span></h5>
        <div class="d-flex align-items-center">
          <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
            <i class="bi bi-box-arrow-left text-danger"></i>
          </div>
          <div class="ps-3">
            <h6>{{ wait_approve.count }} ใบเบิก</h6>
            <span class="text-success small pt-1 fw-bold">รออนุมัติ </span> <span class="text-muted small pt-2 ps-1">{{ wait_approve.count }} รายการ</span>

          </div>
        </div>
      </div>
    </a>
  </div>
</div>
<div class="col-xxl-4 col-md-6">
  <div class="card info-card bg-card">
    <a href="{% url 'parcel:return_command_list' %}">
      <div class="card-body">
        <h5 class="card-title">รายการใบส่งคืน <span>| รออนุมัติ</span></h5>
        <div class="d-flex align-items-center">
          <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
            <i class="bi bi-box-arrow-in-right text-success"></i>
          </div>
          <div class="ps-3">
            <h6>{{ all_return_wait_approve.count }} ใบส่งคืน</h6>
            <span class="text-success small pt-1 fw-bold">รออนุมัติ </span> <span class="text-muted small pt-2 ps-1">{{ return_wait_approve.count }} รายการ</span>

          </div>
        </div>
      </div>
    </a>
  </div>
</div>

parcel/templates/parcel/components/modal_approve_bill.html
{% load tags %}
    <!-- modal for enter pin to approve bill -->
    <div class="modal fade" id="approve_bill">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">ยืนยันการอนุมัติ</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="post"
                action="{% url 'parcel:approve_bill' pk=bill.pk %}"
                id="approve_bill"
                class="pin-code">
            <div class="modal-body">

              <p>
              ยืนยันการอนุมัติใบเบิกที่ : {{ bill.pk }}/{{ bill.created_at.year|thaiyear }}
              <br>
              คลังเจ้าของพัสดุ : {{ bill.stock }}
              <br>
              ผู้ขออนุมัติ : {{ bill.billdetail.agent.profile }}
              </p>
              <!-- form to enter pin number to confirm approve -->
              {% csrf_token %}
              <!-- enter password to confirm approve -->
              <input 
                 type="password" 
                 name="pin" 
                 class="form-control" 
                 placeholder="กรุณาใส่รหัสผ่านเพื่ออนุมัติ" 
                 required
                 />
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
              <button type="submit" class="btn btn-primary">ยืนยัน</button>
            </div>
          </form>
        </div>
      </div>
    </div>

parcel/templates/parcel/components/modal_approver_return.html
{% load tags %}
    <!-- modal for enter pin to approve bill -->
    <div class="modal fade" id="approverModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">ยืนยันการอนุมัติ</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="post"
                action="{% url 'parcel:return_approve' pk=bill.pk %}"
                id="approve_bill"
                class="pin-code">
            <div class="modal-body">

              <p>
              ยืนยันการอนุมัติใบส่งคืนที่ : {{ bill.pk }}/{{ bill.created_at.year|thaiyear }}
              <br>
              คลังเจ้าของพัสดุ : {{ bill.stock }}
              <br>
              ผู้ขอส่งคืน : {{ bill.user.profile }}
              </p>
              <!-- form to enter pin number to confirm approve -->
              {% csrf_token %}
              <!-- enter password to confirm approve -->
              <input 
                 type="password" 
                 name="pin" 
                 class="form-control" 
                 placeholder="กรุณาใส่รหัสผ่านเพื่ออนุมัติ" 
                 required
                 />
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
              <button type="submit" class="btn btn-primary">ยืนยัน</button>
            </div>
          </form>
        </div>
      </div>
    </div>

parcel/templates/parcel/components/modal_checker_return.html
{% load tags %}

<!-- modal for request approve -->
<div class="modal fade" id="checkerModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          ตรวจสอบการส่งคืน ใบส่งคืนที่ {{ bill.pk }}/{{ bill.created_at.year|thaiyear }}
        </h5>
        <button type="button"
          class="btn-close" 
          data-bs-dismiss="modal" 
          aria-label="Close"
        >
        </button>
      </div>
      <div class="modal-body">
        <form method="post"
          action="{% url 'parcel:checker_confirm_return' pk=bill.pk %}"
          id="checker_confirm_return"
          class="pin-code"
        >
          <div class="modal-body">

            <p> ตรวจสอบแล้วเห็นว่า </p>
            <!-- form to enter pin number to confirm approve -->
            {% csrf_token %}

            <textarea id="note" name="note" rows="3" class="form-control" placeholder="ตรวจสอบแล้วเห็นว่า"></textarea>
            <br>

            <!-- enter password to confirm approve -->

            <input type="password" 
              name="pin" 
              class="form-control" 
              placeholder="กรุณาใส่รหัสผ่านเพื่อยืนยัน" 
              required
            />
          </div>
          <div class="modal-footer">
            <button type="button" 
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              ยกเลิก
            </button>
            <button type="submit"
              class="btn btn-primary"
              id="btnCheckerConfirm"
            >
              ยืนยัน
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
$(function(){
  $('#btnCheckerConfirm').click(function(){
    $('#btnCheckerConfirm').prop('disabled', true);
    let form = $('#checker_confirm_return');
    form.submit();
    });
  }
</script>

parcel/templates/parcel/components/modal_confirm_reject.html
{% load tags %}
    <!-- modal for confirm_reject -->
    <div class="modal fade" id="reject_bill">
      <div class="modal-dialog">
        <form action="{% url 'parcel:reject_bill' pk=bill.pk %}">
          {% csrf_token %}
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">ยืนยันการไม่อนุมัติ</h5>
            </div>
            <div class="modal-body" id="reject_reason">
              <p>เหตุผลที่ไม่อนุมัติ</p>
              <textarea class="form-control" name="note" id="note" cols="30" rows="3"></textarea>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
              <button type="submit" class="btn btn-primary">ยืนยัน</button>
            </div>
          </div>
        </form>
      </div>
    </div>

parcel/templates/parcel/components/modal_request_bill.html
{% load tags %}
    <div class="modal fade" id="request_approve">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">ยืนยันการขออนุมัติ</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="post"
                action="{% url 'parcel:request_approve' pk=bill.pk %}"
                id="request_bill_form"
                class="pin-code">
            <div class="modal-body">
              <!-- form to enter pin number to confirm approve -->
              {% csrf_token %}
              <p>เพื่อขออนุมัติ ใบเบิกที่ {{ bill.pk }}/{{ bill.created_at.year|thaiyear }}</p>

              <p>
              {% for item in items %}
              {{ forloop.counter }}.{{ item.category }} 
              <br> &nbsp;&nbsp;&nbsp; - หมายเลข {{ item.item.serial }}
              <br> &nbsp;&nbsp;&nbsp; - จำนวน {{ item.quantity }} {{ item.count_text|default:"หน่วย" }}
              <br>{% if not forloop.last %}
              <hr>
              {% endif %}
              {% endfor %}
              </p>

              <!-- text input for ParcelRequestNote -->
              <label for="note">หมายเหตุ</label>
              <input type="textarea" name="note" class="form-control" style="margin-bottom: 10px;" placeholder="ตรวจสอบแล้วเห็นว่า" autocomplete="off">
              <!-- enter password to confirm approve -->

              <!-- <p>กรุณาใส่รหัสผ่าน</p> -->
              <input type="password" name="pin" class="form-control" placeholder="กรุณาใส่รหัสผ่านเพื่อขออนุมัติ" required>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
              <button type="submit" class="btn btn-primary">ยืนยัน</button>
            </div>
          </form>
        </div>
      </div>
    </div>

parcel/templates/parcel/components/modal_set_item.html
{% load tags %}
    <!-- modal for set item location -->
    <div class="modal fade" id="set_item">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">ติดตั้ง</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="post"
                action="{% url 'parcel:set_item' %}"
                id="set_item_form"
                class="pin-code">
            <div class="modal-body">
              <!-- form to enter pin number to confirm approve -->


              <!-- show object item from data-bs-object -->
              <p id="pk"></p>
              <h3 id='show_data'></h3>

              <!-- add location to select set location to item -->
              {% csrf_token %}

              <!-- select location -->
              <select name="location" class="form-select">
                <option value=""></option>
                {% for item in locations %}
                <option value="{{ item.pk }}">{{ item }}</option>
                {% endfor %}
              </select>

              <br />

              <!-- enter password to confirm approve -->

              <!-- <p>กรุณาใส่รหัสผ่าน</p> -->
              <input
              type="password"
              name="pin-set-item"
              class="form-control"
              placeholder="กรุณาใส่รหัสผ่านเพื่อยืนยันการติดตั้ง"
              style="margin-top: 10px;"
              required
              >
              <input type="hidden" name='item_pk' id="item_pk" value="">

            </div>
            <div class="modal-footer">
              <button id="submit" type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
              <button ="submit" class="btn btn-primary">ยืนยัน</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <script>
      $(document).on('click', '#set_item_btn', function(){
        var data = $(this).data('object');
        $('#show_data').html(data);
        var pk = $(this).data('pk');
        $('#set_item').modal('show');
        $("#item_pk").val(pk);
      });

    </script>

parcel/templates/parcel/components/user_card.html
<div class="col-xxl-4 col-md-6">
  <div class="card info-card bg-card">
    <a href="{% url 'parcel:bill_list' %}">
      <div class="card-body">
        <h5 class="card-title">รายการใบเบิก <span>| {{ request.user.profile }}</span></h5>
        <div class="d-flex align-items-center">
          <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
            <i class="bi bi-clipboard-plus text-info"></i>
          </div>
          <div class="ps-3">
            <h6>{{ all_bill.count }} ใบเบิก</h6>
            <span class="text-success small pt-1 fw-bold">รออนุมัติ </span> <span class="text-muted small pt-2 ps-1">
              {{ wait_approve.count }} รายการ</span>
            <span class="text-success small pt-1 fw-bold">ร่าง </span> <span class="text-muted small pt-2 ps-1">
              {{ bill_draft.count }} รายการ</span>

          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<div class="col-xxl-4 col-md-6">
  <div class="card info-card bg-card">
    <a href="{% url 'parcel:return_parcel_list' %}">
      <div class="card-body">
        <h5 class="card-title">รายการใบส่งคืน <span>| {{ request.user.profile }}</span></h5>
        <div class="d-flex align-items-center">
          <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
            <i class="bi bi-clipboard-minus text-warning"></i>
          </div>
          <div class="ps-3">
            <h6>{{ all_return.count }} ใบส่งคืน</h6>
            <span class="text-success small pt-1 fw-bold">รออนุมัติ </span> <span class="text-muted small pt-2 ps-1">
              {{ return_wait_approve.count }} รายการ</span>
            <span class="text-success small pt-1 fw-bold">ร่าง </span> <span class="text-muted small pt-2 ps-1">
              {{ return_draft.count }} รายการ</span>

          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<div class="col-xxl-4 col-md-6">
  <div class="card info-card bg-card">
    <a href="{% url 'parcel:parcel_list' %}">
      <div class="card-body">
        <h5 class="card-title">รายการพัสดุ <span>| {{ request.user.profile }}</span></h5>
        <div class="d-flex align-items-center">
          <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
            <i class="bi bi-cart4 text-danger"></i>
          </div>
          <div class="ps-3">
            <h6>{{ parcel_list.count }} รายการ</h6>
            <span class="text-success small pt-1 fw-bold">รับแล้ว</span> <span class="text-muted small pt-2 ps-1">
              {{ on_hand.count }} รายการ รอการดำเนินการ</span>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>