car/urls.py
from django.urls import include, path

from . import views

app_name = "car"

urlpatterns = [
    path("", views.CarListView.as_view(), name="list"),
    path("create/", views.CarCreateView.as_view(), name="create"),
    path("<int:pk>/", views.CarDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", views.CarUpdateView.as_view(), name="update"),
    path(
        "booking/",
        include(
            [
                path("", views.CarBookingListView.as_view(), name="booking"),
                path(
                    "create/<int:pk>/",
                    views.CarBookingCreateView.as_view(),
                    name="booking-create",
                ),
                path(
                    "detail/<int:pk>/",
                    views.CarBookingDetailView.as_view(),
                    name="booking-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarBookingUpdateView.as_view(),
                    name="booking-update",
                ),
                path("wait/", views.WaitApproveListView.as_view(), name="wait_approve"),
                path(
                    "return/<int:pk>/",
                    views.ReturnCar,
                    name="return-car",
                ),
                path(
                    "approve/<int:pk>/",
                    views.car_booking_approve,
                    name="booking-approve",
                ),
                path(
                    "reject/<int:pk>/",
                    views.car_booking_reject,
                    name="booking-reject",
                ),
                path("use/<int:pk>/", views.UseCar, name="use-car"),
            ]
        ),
    ),
    path(
        "fix/",
        include(
            [
                path("", views.CarRequestFixListView.as_view(), name="fix"),
                path(
                    "create/<int:pk>/",
                    views.CarFixCreateView.as_view(),
                    name="fix-create",
                ),
                path(
                    "<int:pk>/",
                    views.CarRequestFixDetailView.as_view(),
                    name="fix-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarFixUpdateView.as_view(),
                    name="fix-update",
                ),
                path(
                    "after-fix/<int:pk>/",
                    views.CarAfterFixView,
                    name="after-fix",
                ),
                path(
                    "my-fix/",
                    views.ResponsibleListView.as_view(),
                    name="my-fix",
                ),
                path("refuel/<int:pk>/", views.RefuelCar, name="refuel"),
            ]
        ),
    ),
    # path('return/<int:pk>/', views.ReturnCar.as_view(), name='return-car'),
]

config/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : urls.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Sep, 22 2022, 15:06 265
# Last Modified Date: Mon Jun, 24 2024, 16:01 176
# Last Modified By  : lu5her <lu5her@mail>
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# for test template
from django.views.generic import TemplateView

from account import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("test/", TemplateView.as_view(template_name="test.html"), name="test"),
    # url for under development page
    path(
        "develop/", TemplateView.as_view(template_name="under_dev.html"), name="develop"
    ),
    path("", views.HomeView.as_view(), name="home"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    # internal url
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("announce/", include("announce.urls")),
    path("document/", include("document.urls")),
    path("journal/", include("journal.urls")),
    path("assign/", include("assign.urls")),
    path("car/", include("car.urls")),
    path("asset/", include("asset.urls")),
    path("inform/", include("inform.urls")),
    path("repair/", include("repair.urls")),
    path("parcel/", include("parcel.urls")),
    path("cart/", include("cart.urls")),
    path(
        "operation/",
        include(
            "operation.urls",
        ),
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

inform/urls.py
from django.urls import path

from . import views

app_name = "inform"

urlpatterns = [
    path("", views.InformHomeView.as_view(), name="home"),
    path("create/", views.InformCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.InformUpdateView.as_view(), name="update"),
    path("all_infrom/", views.all_inform, name="all_inform"),
    path("review/<int:pk>/", views.review_save, name="review"),
    path("pdf/<int:pk>/", views.inform_to_pdf, name="pdf"),
    # user url
    path("user/list/", views.InformUserListView.as_view(), name="user_list"),
    path(
        "department/list/",
        views.InformDepartmentListView.as_view(),
        name="department_list",
    ),
    path("agent/list/", views.InformAgentListView.as_view(), name="agent_list"),
    path("wait/list/", views.InformWaitListView.as_view(), name="wait_list"),
    path("<int:pk>/", views.InformDetailView.as_view(), name="detail"),
    path(
        "customer/wait_to_review/",
        views.customer_wait_to_review,
        name="customer_wait_to_review",
    ),
    # manager url
    path("manager/list/", views.InformManagerListView.as_view(), name="manager_list"),
    path(
        "manager/wait/", views.InformWaitApproveListView.as_view(), name="manager_wait"
    ),
    path("manager/close/", views.staff_wait_close, name="manager_close"),
    # technical url
    path("accept/<int:pk>/", views.accept_inform, name="accept"),
    path("tech/list/", views.InformTechnicalListView.as_view(), name="tech_list"),
    path(
        "tech/progress/", views.InformInProgressListView.as_view(), name="tech_progress"
    ),
    path("tech/note/<int:pk>/", views.repair_note, name="tech_note"),
    path("tech/all_assign/", views.all_assigned, name="tech_all_assign"),
    # command url
    path("command/approve/<int:pk>/", views.inform_approve, name="command_approve"),
    path("command/reject/<int:pk>/", views.inform_reject, name="command_reject"),
    path("wait_close_approve/", views.wait_close_approve, name="wait_close_approve"),
    path(
        "command/wait_approve/", views.command_wait_approve, name="command_wait_approve"
    ),
    path("command/progress/", views.all_progress, name="command_progress"),
    path("command/recheck/", views.all_recheck, name="command_recheck"),
    path("command/close_approve/<int:pk>/", views.close_approve, name="close_approve"),
]

operation/urls.py
from django.urls import include, path

from . import views

app_name = "operation"

urlpatterns = [
    path("", views.OperationHome.as_view(), name="home"),
    path("create", views.OperationCreateView.as_view(), name="create"),
    path("<int:pk>", views.OperationDetailView.as_view(), name="detail"),
    path("leader/<int:pk>/accept", views.accept_leader, name="accept_leader"),
    path(
        "team/",
        include(
            [
                path(
                    "member/create/<int:pk>",
                    views.team_member_create,
                    name="team_member_create",
                ),
                path(
                    "member/delete/<int:pk>",
                    views.delete_team_member,
                    name="member_delete",
                ),
            ]
        ),
    ),
    # for operation car
    path(
        "car/",
        include(
            [
                path(
                    "add/<int:pk>",
                    views.car_operation_add,
                    name="car_operation_add",
                ),
                path("change/<int:pk>", views.change_car, name="change_car"),
                path("delete/<int:pk>", views.delete_car, name="delete_car"),
            ]
        ),
    ),
    # for operation task
    path(
        "task/",
        include(
            [
                path("add/<int:pk>", views.operation_task_add, name="add_task"),
                path(
                    "delete/<int:pk>",
                    views.operation_task_delete,
                    name="delete_task",
                ),
                path("add_note/<int:pk>", views.operation_note_add, name="add_note"),
            ]
        ),
    ),
    # for oil reimburesment
    path(
        "fuel/",
        include(
            [
                path("add/<int:pk>", views.request_fuel, name="add_fuel"),
                path("update/<int:pk>", views.edit_fuel, name="edit_fuel"),
                path("delete/<int:pk>", views.delete_fuel_request, name="delete_fuel"),
            ]
        ),
    ),
    # for allowance
    path(
        "allowance/",
        include(
            [
                path("add/<int:pk>", views.allowance_add, name="allowance_add"),
                path(
                    "delete/<int:pk>",
                    views.allowance_delete,
                    name="allowance_delete",
                ),
                path(
                    "refund/<int:pk>",
                    views.allowance_refund,
                    name="allowance_refund",
                ),
                path(
                    "refund/update/<int:pk>",
                    views.allowance_refund_update,
                    name="allowance_refund_update",
                ),
                path(
                    "refund/delete/<int:pk>",
                    views.allowance_refund_delete,
                    name="allowance_refund_delete",
                ),
            ]
        ),
    ),
    # for parcel document
    path(
        "parcel/",
        include(
            [
                path(
                    "request/add/<int:pk>",
                    views.parcel_requests_add,
                    name="parcel_request_add",
                ),
                path(
                    "request/delete/<int:pk>",
                    views.parcel_requests_delete,
                    name="parcel_request_delete",
                ),
                path(
                    "return/add/<int:pk>",
                    views.parcel_return_add,
                    name="parcel_return_add",
                ),
                path(
                    "return/delete/<int:pk>",
                    views.parcel_return_delete,
                    name="parcel_return_delete",
                ),
            ]
        ),
    ),
    # for request open/close and approve that
    path(
        "approve/",
        include(
            [
                path("request/open/<int:pk>", views.request_open, name="request_open"),
                path("open/<int:pk>", views.approve_open, name="approve_open"),
                path(
                    "request/close/<int:pk>", views.request_close, name="request_close"
                ),
                path("close/<int:pk>", views.approve_close, name="approve_close"),
            ]
        ),
    ),
    # for inform
    path(
        "inform/",
        include(
            [
                path("add/<int:pk>", views.add_inform, name="add_inform"),
                path("delete/<int:pk>", views.delete_inform, name="delete_inform"),
            ]
        ),
    ),
    path(
        "update_date/<int:pk>",
        views.update_operation_date,
        name="update_date",
    ),
    # operation list for member
    path(
        "member/operation_list",
        views.OperationMemberListView.as_view(),
        name="member_operation_list",
    ),
    # for command
    path(
        "command/",
        include(
            [
                path(
                    "wait/open/",
                    views.OperationCommandWaitOpenListView.as_view(),
                    name="command_wait_open",
                ),
                path(
                    "wait/close/",
                    views.OperationCommandWaitCloseListView.as_view(),
                    name="command_wait_close",
                ),
                path("open/<int:pk>", views.approve_open, name="approve_open"),
                path("close/<int:pk>", views.approve_close, name="approve_close"),
                path(
                    "overview/",
                    views.OperationCommandOverviewListView.as_view(),
                    name="command_overview",
                ),
                path(
                    "overview/stats/",
                    views.OperationOverviewTemplateView.as_view(),
                    name="overview",
                ),
            ]
        ),
    ),
    # for render pdf
    path("operation/<int:pk>/pdf/", views.operation_to_pdf, name="operation_to_pdf"),
]

operation/templates/operation/buttons/command.html
{% load tags %}

<form method="POST" action="" id="form_approve_command">
  {% csrf_token %}
  <button class="btn btn-lg btn-secondary back">ย้อนกลับ</button>
  <!-- button to generate pdf -->
  <a href="{% url 'operation:operation_to_pdf' pk=object.pk %}" target="_blank" class="btn btn-lg btn-primary" id="inform_pdf">พิมพ์</a>
  <!-- <button type="button" data-bs-toggle="modal" data-bs-target="#informPdfModal" class="btn btn-lg btn-primary" id="inform_pdf">พิมพ์</button> -->

  {% if object.approve_status == 'WO' %}

  <button type="button" data-bs-toggle="modal" data-bs-target="#approveOpenModal" class="btn btn-lg btn-success" id="approve_open">อนุมัติเปิดงาน</button>

  {% elif object.approve_status == 'WC' %}

  <button type="button" class="btn btn-lg btn-warning" id="approve_close">อนุมัติปิดงาน</button>

  {% endif %}
</form>

<!-- modal for approve_open -->
<div class="modal fade" id="approveOpenModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">อนุมัติเปิดงาน</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>คุณต้องการอนุมัติเปิดงานหรือไม่?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
        <button type="button" class="btn btn-primary" id="approve_open_confirm">อนุมัติเปิดงาน</button>
      </div>
    </div>
  </div>
</div>
<!-- modal for approve_close -->
<div class="modal fade" id="approveCloseModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">อนุมัติปิดงาน</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>คุณต้องการอนุมัติปิดงานหรือไม่?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
        <button type="button" class="btn btn-primary" id="approve_close_confirm">อนุมัติปิดงาน</button>
      </div>
    </div>
  </div>
</div>

<!-- modal for inform_pdf -->
<div class="modal fade" id="informPdfModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">พิมพ์รายละเอียดงาน</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>คุณต้องการพิมพ์รายละเอียดงานหรือไม่?</p>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="informRadio" id="informRadio1" value="yes">
          <label class="form-check-label" for="informRadio1">
            พิมพ์รายละเอียดงาน
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="informRadio" id="informRadio2" value="no">
          <label class="form-check-label" for="informRadio2">
            ไม่พิมพ์รายละเอียดงาน
          </label>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">ยกเลิก</button>
        <button type="button" class="btn btn-primary" id="inform_pdf_confirm">พิมพ์</button>
      </div>
    </div>
  </div>
</div>



<script>
$(document).ready(function () {
  $("#approve_open, #approve_close").click(function () {
    const url = $(this).attr('id') === 'approve_open'
      ? `{% url 'operation:approve_open' pk=object.pk %}`
      : `{% url 'operation:approve_close' pk=object.pk %}`;
    $("#form_approve_command").attr("action", url).submit();
  });
});
</script>

operation/templates/operation/buttons/creator.html
{% load tags %}

<form method="POST" action="" id="form_approve">
  {% csrf_token %}
  <button class="btn btn-lg btn-secondary back">ย้อนกลับ</button>
  <!-- button to generate pdf -->
  <a href="{% url 'operation:operation_to_pdf' pk=object.pk %}" target="_blank" class="btn btn-lg btn-primary" id="inform_pdf">พิมพ์</a>

  <!-- TODO: add condition to request open and close operation -->
  {% if object.approve_status == "AP" %}
  <button type="button" class="btn btn-lg btn-success" id="request_close">ขออนุมัติปิดงาน</button>

  {% elif object.approve_status == 'DF' %}

  <button type="button" class="btn btn-lg btn-warning" id="request_open">ขออนุมัติเปิดงาน</button>

  {% endif %}
</form>

<script>
// on ready
$(document).ready(function () {
  $("#request_open, #request_close").click(function () {
    const url = $(this).attr('id') === 'request_open'
      ? `{% url 'operation:request_open' pk=object.pk %}`
      : `{% url 'operation:request_close' pk=object.pk %}`;
    $("#form_approve").attr("action", url).submit();
  });
});
</script>

operation/templates/operation/buttons/leader.html
{% load tags %}

<a href="{% url 'inform:tech_list' %}" class="btn btn-lg btn-secondary">ย้อนกลับ</a>

operation/templates/operation/buttons/manager.html
{% load tags %}

<a href="{% url 'inform:manager_list' %}" class="btn btn-lg btn-secondary">ย้อนกลับ</a>

{% if customer_review and object.repair_status == 'CLO' and manager_review is None %}
<button type="button" class="btn btn-lg btn-success" data-bs-toggle="modal"
  data-bs-target="#reviewModal">Review</button>
{% endif %}

{% if not object.repair_category %}
<button type="button" class="btn btn-lg btn-success" data-bs-toggle="modal"
  data-bs-target="#manager_check">จัดการ</button>
{% endif %}

operation/templates/operation/buttons/user.html
<a href="{% url 'inform:department_list' %}" class="btn btn-lg btn-secondary">ย้อนกลับ</a>