account/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : urls.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Sep, 29 2022, 15:34 272
# Last Modified Date: Fri Dec, 02 2022, 19:27 336
# Last Modified By  : lu5her <lu5her@mail>
from django.urls import path

from account import views

app_name = "account"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile-update/", views.update_profile, name="profile-update"),
    path("change-password/", views.ChangePassword.as_view(), name="change-password"),
    path("members/", views.MembersListView.as_view(), name="members"),
    path("member/<int:pk>/", views.MembersDetailView.as_view(), name="member"),
    # path("sectors/<int:sector_pk>/", views.sector_list, name="sectors"),
    # path("positions/<int:position_pk>/", views.position_list, name="positions"),
    path(
        "profiles/<str:filter_type>/<int:pk>/",
        views.ProfileListView.as_view(),
        name="profile_list",
    ),
    # check username
    path("check-username/", views.check_username, name="check-username"),
]

assign/urls.py
from django.urls import path

from assign import views

app_name = 'assign'

urlpatterns = [
    path('', views.AssignHomeView.as_view(), name='home'),
    path('user/', views.AssignListView.as_view(), name='list'),
    path('staff/', views.AssignStaffListView.as_view(), name='staff-list'),
    path('<int:pk>/', views.AssignDetailView.as_view(), name='detail'),
    path('create/', views.AssignCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.AssignUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.AssignDeleteView.as_view(), name='delete'),

    path('not-accepted/', views.AssignNotAcceptedView.as_view(), name='not-accepted'),

    path('accept/<int:pk>/', views.accepted, name='accept'),
]

car/urls.py
from django.urls import include, path

from . import views

app_name = "car"

urlpatterns = [
    path("", views.CarListView.as_view(), name="list"),
    path("create/", views.CarCreateView.as_view(), name="create"),
    path("<int:pk>/", views.CarDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", views.CarUpdateView.as_view(), name="update"),
    path(
        "booking/",
        include(
            [
                path("", views.CarBookingListView.as_view(), name="booking"),
                path(
                    "create/<int:pk>/",
                    views.CarBookingCreateView.as_view(),
                    name="booking-create",
                ),
                path(
                    "detail/<int:pk>/",
                    views.CarBookingDetailView.as_view(),
                    name="booking-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarBookingUpdateView.as_view(),
                    name="booking-update",
                ),
                path("wait/", views.WaitApproveListView.as_view(), name="wait_approve"),
                path(
                    "return/<int:pk>/",
                    views.ReturnCar,
                    name="return-car",
                ),
                path(
                    "approve/<int:pk>/",
                    views.car_booking_approve,
                    name="booking-approve",
                ),
                path(
                    "reject/<int:pk>/",
                    views.car_booking_reject,
                    name="booking-reject",
                ),
                path("use/<int:pk>/", views.UseCar, name="use-car"),
            ]
        ),
    ),
    path(
        "fix/",
        include(
            [
                path("", views.CarRequestFixListView.as_view(), name="fix"),
                path(
                    "create/<int:pk>/",
                    views.CarFixCreateView.as_view(),
                    name="fix-create",
                ),
                path(
                    "<int:pk>/",
                    views.CarRequestFixDetailView.as_view(),
                    name="fix-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarFixUpdateView.as_view(),
                    name="fix-update",
                ),
                path(
                    "after-fix/<int:pk>/",
                    views.CarAfterFixView,
                    name="after-fix",
                ),
                path(
                    "my-fix/",
                    views.ResponsibleListView.as_view(),
                    name="my-fix",
                ),
                path("refuel/<int:pk>/", views.RefuelCar, name="refuel"),
            ]
        ),
    ),
    # path('return/<int:pk>/', views.ReturnCar.as_view(), name='return-car'),
]

config/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : urls.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Sep, 22 2022, 15:06 265
# Last Modified Date: Mon Jun, 24 2024, 16:01 176
# Last Modified By  : lu5her <lu5her@mail>
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# for test template
from django.views.generic import TemplateView

from account import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("test/", TemplateView.as_view(template_name="test.html"), name="test"),
    # url for under development page
    path(
        "develop/", TemplateView.as_view(template_name="under_dev.html"), name="develop"
    ),
    path("", views.HomeView.as_view(), name="home"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    # internal url
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("announce/", include("announce.urls")),
    path("document/", include("document.urls")),
    path("journal/", include("journal.urls")),
    path("assign/", include("assign.urls")),
    path("car/", include("car.urls")),
    path("asset/", include("asset.urls")),
    path("inform/", include("inform.urls")),
    path("repair/", include("repair.urls")),
    path("parcel/", include("parcel.urls")),
    path("cart/", include("cart.urls")),
    path(
        "operation/",
        include(
            "operation.urls",
        ),
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

document/urls.py
from django.urls import path

from document import views

app_name = 'document'

urlpatterns = [
    path('', views.DocumentHomeView.as_view(), name='home'),
    path('create/', views.DocumentCreateView.as_view(), name='create'),
    path('inbox/', views.InboxListView.as_view(), name='inbox'),
    path('inbox/<int:pk>/', views.InboxDetailView.as_view(), name='inbox-detail'),
    path('outbox/', views.OutboxListView.as_view(), name='outbox'),
    path('outbox/<int:pk>/', views.OutboxDetailView.as_view(), name='outbox-detail'),
    path('accept/<int:pk>/', views.accept_document, name='accept'),
]

assign/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : models.py
# Author            : lu5her <lu5her@mail>
# Date              : Fri Oct, 28 2022, 21:17 301
# Last Modified Date: Wed Dec, 04 2024, 21:40 339
# Last Modified By  : lu5her <lu5her@mail>
from datetime import datetime

from account.models import Profile
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from inform.models import Inform

# Create your models here.


def get_image_name(instance, filename):
    """get_image_name.

    :param instance:
    :param filename:
    """
    file_name = instance.title
    # return 'Assign/{}/{}'.format(file_name, filename)
    return f"Assign/{file_name}/{filename}"


class Assign(models.Model):
    """
    Assign model for assigning tasks to users.

    Attributes:
        title:
        body:
        author:
        created_at:
        assigned_to:
        accepted:
        accepted_on:
        status:
        note:
    """

    class Status(models.TextChoices):
        """
        Status choices for Assign model.

        Attributes:
            PENDING:
            ACCEPTED:
            REJECTED:
            DONE:
        """

        PENDING = "Pending", "รอตอบรับ"
        ACCEPTED = "Accepted", "ตอบรับแล้ว"
        REJECTED = "Rejected", "ปฏิเสธ"
        DONE = "Done", "เสร็จสมบูรณ์"

    title = models.CharField(max_length=200)
    # body        = models.TextField()
    body = models.TextField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="assignAuthor"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    assigned_to = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="assigned_to"
    )
    accepted = models.BooleanField(default=False)
    accepted_on = models.DateTimeField("date accepted", null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )
    note = models.TextField(null=True, blank=True)
    ref_inform = models.ForeignKey(
        Inform,
        on_delete=models.CASCADE,
        related_name="assigned_ref_inform",
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Assign"
        verbose_name_plural = "Assign"

    def save(self, *args, **kwargs):
        if self.accepted and self.accepted_on is None:
            self.accepted_on = datetime.now()
            self.status = self.Status.ACCEPTED
        elif not self.accepted and self.accepted_on is not None:
            self.accepted_on = None
        super(Assign, self).save(*args, **kwargs)

        def __str__(self):
            # return self.title, self.author.get_full_name(), self.created_at, self.assigned_to.get_full_name(),
            return f"{self.title} to {self.assigned_to.get_full_name()} on {self.created_at.strftime('%a, %d %b %Y %H:%M')}"


class AssignImage(models.Model):
    """AssignImage."""

    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    images = models.ImageField(upload_to=get_image_name, null=True, blank=True)

    class Meta:
        verbose_name = "Images"
        verbose_name_plural = "Images"

    def __str__(self):
        return f"{self.assign.title}"


class AssignProgress(models.Model):
    """For Update Assign Progress"""

    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    note = models.TextField(null=True, blank=True)
    status = models.CharField(
        max_length=20, choices=Assign.Status.choices, default=Assign.Status.PENDING
    )

    class Meta:
        verbose_name = "Progress"
        verbose_name_plural = "Progress"

    def __str__(self):
        return (
            f"{self.assign.title} on {self.created_at.strftime('%a, %d %b %Y %H:%M')}"
        )

assign/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : forms.py
# Author            : lu5her <lu5her@mail>
# Date              : Fri Oct, 28 2022, 21:13 301
# Last Modified Date: Fri Nov, 11 2022, 22:58 315
# Last Modified By  : lu5her <lu5her@mail>
from account.models import Profile
from django import forms
from django.forms import widgets

from assign.models import Assign, AssignImage, AssignProgress


class AssignModelChoice(forms.ModelChoiceField):
    def label_form_instance(self, obj):
        if obj.profile.rank:
            return obj.get_full_name()
        else:
            return obj.user.username


class AssignForm(forms.ModelForm):
    """
    Form for assign model

    Attributes:
        queryset:
    """

    def __init__(self, current_user, *args, **kwargs):
        super(AssignForm, self).__init__(*args, **kwargs)
        # user = User.objects.get(user=current_user)
        self.fields["assigned_to"].queryset = Profile.objects.exclude(pk=current_user)

    class Meta:
        model = Assign
        fields = (
            "title",
            "body",
            "author",
            "assigned_to",
        )
        widgets = {
            "title": widgets.TextInput(attrs={"class": "form-control"}),
            "body": widgets.Textarea(attrs={"class": "form-control"}),
            "assigned_to": widgets.Select(
                attrs={"class": "form-select", "placeholder": "เลือกผู้ปฏิบัติงาน"}
            ),
            "author": widgets.HiddenInput(
                attrs={"class": "form-control", "id": "author"}
            ),
        }
        labels = {
            "title": "ชื่อเรื่อง",
            "body": "รายละเอียด",
            "author": "ผู้เขียน",
            "assigned_to": "มอบงานหมายให้",
        }


class ProgressForm(forms.ModelForm):
    """
    Form for update progress

    Attributes:
        queryset:
    """

    class Meta:
        model = Assign
        fields = ("status",)

        widgets = {
            "status": widgets.Select(attrs={"class": "form-select"}),
            #'note': widgets.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            "status": "สถานะการดำเนินการ",
        }


class NoteForm(forms.ModelForm):
    """
    Form for update note

    Attributes:
        queryset:
    """

    class Meta:
        model = AssignProgress
        fields = ("note",)

        widgets = {
            "note": widgets.Textarea(attrs={"class": "form-control", "rows": 3}),
        }

        labels = {
            "note": "บันทึก",
        }


class CloseAssignForm(forms.ModelForm):
    """
    Form for close assign
    """

    class Meta:
        model = AssignImage
        fields = ("images",)

        widgets = {
            "images": widgets.FileInput(
                attrs={"class": "form-control", "required": False}
            ),
        }
        labels = {
            "images": "ภาพการทำงาน",
        }

assign/templates/assign/components/detail_tab.html
{% load tags %}
<h6 class="card-title"> รายละเอียด | <span> {{ object.title }}</span></h6>
<table class="table">
  <tr>
    <th>เรื่อง</th>
    <td>{{ object.title }}</td>
  </tr>

  <tr>
    <th>มอบหมายให้</th>
    <td>{{ object.assigned_to.rank }}{{ object.assigned_to.user.get_full_name }}</td>
  </tr>

  <tr>
    <th>ผู้มอบหมาย</th>
    <td>{{ object.author.profile }}</td>
  </tr>

  <tr>
    <th>สถานะ</th>
    {% if object.accepted %}
    <td>
      <i class="bi bi-check-circle" style="color: green;"></i>
      ตอบรับแล้ว เมื่อ<br>
      {{ object.accepted_on|thaidate }} เวลา 
      {{ object.accepted_on|date:"H:i" }} น.
    </td>
    {% else %}
    <td>
      <i class="bi bi-x-circle" style="color:red"></i>
      ยังไม่ตอบรับ
    </td>
    {% endif %}
  </tr>

  <tr>
    <th>สร้างเมื่อ</th>
    <td>{{ object.created_at|thaidate }} 
      เวลา {{ object.created_at|date:"H:i" }} น.
    </td>
  </tr>
</table>

<table class="table table-borderless">
  <tr>
    <th class="text-center">รายละเอียด</th>
  </tr>
  <tr>
    <td>{{ object.body|safe|linebreaks }}</td>
  </tr>
</table>

assign/templates/assign/components/notes_tab.html
{% load tags %}
{% if note %}
<h5 class="card-title">บันทึกการทำงาน | <span>{{ object.title }}</span></h5>
<table class="table table-borderless">
  {% for n in note %}
  <tr style="border-bottom: 2px dashed grey;">
    {% if n.status is not None %}<td>({{ n.get_status_display }})</td>{% endif %}
    <td>{{ n.note|linebreaks }}</td>
    <td>{{ n.created_at|thaidate }} เวลา {{ n.created_at|date:"H:m" }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
{% if request.user == object.author %}
<h5><i class="bi bi-x-circle" style="color: red;">ยังไม่ตอบรับการมอบหมายงาน</i></h5>
<p>รอ 
<a href="{% url 'account:member' pk=object.assigned_to.user.pk %}">
  {{ object.assigned_to.rank }} {{ object.assigned_to.user.get_full_name }}
</a> ตอบรับงาน 
</p>
{% comment %}<p><a href="{% url 'account:member' pk=object.assigned_to.user.pk %}">รายละเอียด</a></p>{% endcomment %}
{% endif %}
{% endif %}

{% if request.user.profile == object.assigned_to %}
<h5 class="card-title">การตอบรับการมอบหมาย | <span>{{ object.title }}</span></h5>
{% if not object.accepted %}
<p>
<i class="bi bi-x-circle" style="color: red;"></i> ยังไม่ตอบรับ | 
<span>
  กรุณาตอบรับการมอบหมายงานจาก
  <a href="{% url 'account:member' pk=object.author.pk %}">
    {{ object.author.profile.rank }}{{ object.author.get_full_name }}
  </a>
</span>
</p>
<center>
  <a href="{% url 'assign:accept' pk=object.pk %}" class="btn btn-success">ตอบรับงาน</a>
</center>
{% else %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.media }}
  <div class="row mb-3">
    <label for="{{ form.status.name }}" class="col-md-4 col-lg-3 col-form-label">{{ form.status.label }}</label>
    <div class="col-md-8 col-lg-9">
      {{ form.status }}
    </div>
  </div>

  <div class="row mb-3">
    <label for="{{ Noteform.note.name }}" class="col-md-4 col-lg-3 col-form-label">{{ note_form.note.label }}</label>
    <div class="col-md-8 col-lg-9">
      {{ note_form.note }}
    </div>
  </div>

  <input type="hidden" name="assign_id" value="{{ object.pk }}">
  <button class="btn btn-lg" style="float: right; background-color: purple; color: white;" type="submit">อัพเดท</button>
</form>
{% endif %}
{% endif %}

assign/templates/assign/components/staff_dashboard.html
{% load tags %}
<section class="section dashboard">
  {% comment %}<div class="row">{% endcomment %}
    <div class="row justify-content-center">
      <!-- Inbox card -->
      <div class="col-xxl-4 col-md-6">
        <div class="card info-card bg-card">
          <a href="#">
            <div class="card-body">
              <h5 class="card-title">งานที่มอบหมาย <span>| All</span></h5>
              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bi bi-journal-arrow-up text-danger"></i>
                </div>
                <div class="ps-3">
                  <h6>{{ assign_by_user.count }} งาน</h6>
                  <span class="text-success small pt-1 fw-bold">{{ assign_by_user_not_accepted.count }} งาน</span> <span
                    class="text-muted small pt-2 ps-1">ยังไม่ตอบรับ</span>

                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      <!-- End Inbox -->

      <!-- Outbox card -->
      <div class="col-xxl-4 col-md-6">
        <div class="card info-card bg-card">
          <a href="{% url 'document:outbox' %}">
            <div class="card-body">
              <h5 class="card-title">งานที่แล้วเสร็จ <span>| All</span></h5>
              <div class="d-flex align-items-center">
                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <i class="bi bi-journal-check text-success"></i>
                </div>
                <div class="ps-3">
                  <h6>{{ outbox.count }} งาน</h6>
                  <span class="text-success small pt-1 fw-bold">{{ today_outbox.count }} งาน</span> <span
                    class="text-muted small pt-2 ps-1">วันนี้</span>

                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      <!-- End Outbox -->

    </div>
</section>

assign/templates/assign/components/staff_list.html
{% load tags %}
<thead>
  <tr>
    <th scope="col">เรื่อง</th>
    <th scope="col">มอบหมายให้</th>
    <th scope="col">เมื่อ</th>
    <th scope="col">สถานะ</th>
    <th scope="col">การตอบรับ</th>
    <th scope="col">...</th>
  </tr>
</thead>
<tbody>
  {% for object in object_list %}
  <tr>
    <th>{{ object.title|text_wrap:20 }}</th>
    <td>{{ object.assigned_to.rank }}{{ object.assigned_to.user.get_full_name }}</td>
    <td>{{ object.created_at|thaidate }}</td>
    <td>
      {% if object.status %}
      {{ object.get_status_display }}
      {% else %}
      -
      {% endif %}
    </td>
    <td>
      {% if object.accepted %}
      <i class="bi bi-check-circle" style="color: green"></i>&nbsp;ตอบรับแล้ว
      {% else %}
      <i class="bi bi-x-circle" style="color: red"></i>&nbsp;ยังไม่ตอบรับ
      {% endif %}
    </td>
    <td>
      <a href="{% url 'assign:detail' pk=object.pk %}" class="badge bg-info"><i class="bi bi-info-circle"></i></a>
    </td>
  </tr>
  {% endfor %}
</tbody>

assign/templates/assign/components/user_dashboard.html
{% load tags %}
<section class="section dashboard">
  {% comment %}<div class="row">{% endcomment %}
  <div class="row justify-content-center">
    <!-- Inbox card -->
    <div class="col-xxl-4 col-md-6">
      <div class="card info-card bg-card">
        <a href="{% url 'document:inbox' %}">
          <div class="card-body">
            <h5 class="card-title">งานที่ถูกมอบหมาย <span>| All</span></h5>
            <div class="d-flex align-items-center">
              <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                <i class="bi bi-layer-backward text-danger"></i>
              </div>
              <div class="ps-3">
                <h6>{{ inbox.count }} ฉบับ</h6>
                <span class="text-success small pt-1 fw-bold">{{ new_inbox }} ฉบับ</span> <span
                  class="text-muted small pt-2 ps-1">ยังไม่ตอบรับ</span>

              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <!-- End Inbox -->

    <!-- Outbox card -->
    <div class="col-xxl-4 col-md-6">
      <div class="card info-card bg-card">
        <a href="{% url 'document:outbox' %}">
          <div class="card-body">
            <h5 class="card-title">กล่องขาออก <span>| All</span></h5>
            <div class="d-flex align-items-center">
              <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                <i class="bi bi-layer-forward text-success"></i>
              </div>
              <div class="ps-3">
                <h6>{{ outbox.count }} ฉบับ</h6>
                <span class="text-success small pt-1 fw-bold">{{ today_outbox.count }} ฉบับ</span> <span
                  class="text-muted small pt-2 ps-1">วันนี้</span>

              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    <!-- End Outbox -->

  </div>
</section>

assign/templates/assign/components/user_list.html
{% load tags %}
<thead>
  <tr>
    <th scope="col">เรื่อง</th>
    <th scope="col">ผู้มอบหมาย</th>
    <th scope="col">มอบหมายเมื่อ</th>
    <th scope="col">สถานะ</th>
    <th scope="col">การตอบรับ</th>
    <th scope="col">...</th>
  </tr>
</thead>
<tbody>
  {% for object in object_list %}
  <tr>
    <td>{{ object.title|text_wrap:20 }}</td>
    <td>{{ object.author.profile.rank }}{{ object.author.get_full_name }}</td>
    <td>{{ object.created_at|thaidate }}</td>
    <td>
      {% if object.status %}
      {{ object.get_status_display }}
      {% else %}
      -
      {% endif %}
    </td>
    {% comment %}<td>{{ object.accepted }}</td>{% endcomment %}
    <td>
      {% if object.accepted %}
      <i class="bi bi-check-circle" style="color:green"></i>&nbsp;ตอบรับแล้ว
      {% else %}
      <i class="bi bi-x-circle" style="color:red"></i>&nbsp;ยังไม่ตอบรับ
      {% endif %}
    </td>
    <td>
      <a href="{% url 'assign:detail' pk=object.pk %}" class="badge bg-info"><i class="bi bi-info-circle"></i></a>
    </td>
  </tr>
  {% endfor %}
</tbody>