asset/urls.py
from django.urls import path

from asset import views

app_name = "asset"

urlpatterns = [
    path("", views.StockItemHomeView.as_view(), name="stockitem_home"),
    path("list/", views.StockItemListView.as_view(), name="stockitem_list"),
    path("<int:pk>/", views.StockItemDetailView.as_view(), name="stockitem_detail"),
    path("add-item/", views.StockItemCreateView.as_view(), name="stockitem_create"),
    path(
        "update/<int:pk>/", views.StockItemUpdateView.as_view(), name="stockitem_update"
    ),
    path("manager/home/", views.StockManageHomeView.as_view(), name="manager_home"),
    path("manager/list/", views.StockManagerListView.as_view(), name="manager_list"),
    path("category/<int:pk>/", views.categories_list, name="category_list"),
    path("manufacturer/<int:pk>/", views.manufacturer_list, name="manufacturer_list"),
    path("network/<int:pk>/", views.network_list, name="network_list"),
    path(
        "department/list/",
        views.StockDepartmentListView.as_view(),
        name="department_list",
    ),
    path(
        "delete/<int:pk>/", views.StockItemDeleteView.as_view(), name="stockitem_delete"
    ),
]

car/urls.py
from django.urls import include, path

from . import views

app_name = "car"

urlpatterns = [
    path("", views.CarListView.as_view(), name="list"),
    path("create/", views.CarCreateView.as_view(), name="create"),
    path("<int:pk>/", views.CarDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", views.CarUpdateView.as_view(), name="update"),
    path(
        "booking/",
        include(
            [
                path("", views.CarBookingListView.as_view(), name="booking"),
                path(
                    "create/<int:pk>/",
                    views.CarBookingCreateView.as_view(),
                    name="booking-create",
                ),
                path(
                    "detail/<int:pk>/",
                    views.CarBookingDetailView.as_view(),
                    name="booking-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarBookingUpdateView.as_view(),
                    name="booking-update",
                ),
                path("wait/", views.WaitApproveListView.as_view(), name="wait_approve"),
                path(
                    "return/<int:pk>/",
                    views.ReturnCar,
                    name="return-car",
                ),
                path(
                    "approve/<int:pk>/",
                    views.car_booking_approve,
                    name="booking-approve",
                ),
                path(
                    "reject/<int:pk>/",
                    views.car_booking_reject,
                    name="booking-reject",
                ),
                path("use/<int:pk>/", views.UseCar, name="use-car"),
            ]
        ),
    ),
    path(
        "fix/",
        include(
            [
                path("", views.CarRequestFixListView.as_view(), name="fix"),
                path(
                    "create/<int:pk>/",
                    views.CarFixCreateView.as_view(),
                    name="fix-create",
                ),
                path(
                    "<int:pk>/",
                    views.CarRequestFixDetailView.as_view(),
                    name="fix-detail",
                ),
                path(
                    "update/<int:pk>/",
                    views.CarFixUpdateView.as_view(),
                    name="fix-update",
                ),
                path(
                    "after-fix/<int:pk>/",
                    views.CarAfterFixView,
                    name="after-fix",
                ),
                path(
                    "my-fix/",
                    views.ResponsibleListView.as_view(),
                    name="my-fix",
                ),
                path("refuel/<int:pk>/", views.RefuelCar, name="refuel"),
            ]
        ),
    ),
    # path('return/<int:pk>/', views.ReturnCar.as_view(), name='return-car'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:category_id>/', views.cart_add, name='cart_add'),
    path('update/<int:category_id>/', views.update_cart, name='update_cart'),
    path('remove/<int:category_id>/', views.cart_remove, name='cart_remove'),
    path('remain/<int:category_id>/', views.remain_in_stock, name='remain_in_stock'),
]

config/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : urls.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Sep, 22 2022, 15:06 265
# Last Modified Date: Mon Jun, 24 2024, 16:01 176
# Last Modified By  : lu5her <lu5her@mail>
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# for test template
from django.views.generic import TemplateView

from account import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("test/", TemplateView.as_view(template_name="test.html"), name="test"),
    # url for under development page
    path(
        "develop/", TemplateView.as_view(template_name="under_dev.html"), name="develop"
    ),
    path("", views.HomeView.as_view(), name="home"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    # internal url
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("announce/", include("announce.urls")),
    path("document/", include("document.urls")),
    path("journal/", include("journal.urls")),
    path("assign/", include("assign.urls")),
    path("car/", include("car.urls")),
    path("asset/", include("asset.urls")),
    path("inform/", include("inform.urls")),
    path("repair/", include("repair.urls")),
    path("parcel/", include("parcel.urls")),
    path("cart/", include("cart.urls")),
    path(
        "operation/",
        include(
            "operation.urls",
        ),
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

asset/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# File              : models.py
# Author            : lu5her <lu5her@mail>
# Date              : Thu Apr, 18 2024, 18:51 109
# Last Modified Date: Fri Apr, 19 2024, 16:36 110
# Last Modified By  : lu5her <lu5her@mail>
# -----
from account.models import Department
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse

# Create your models here.


# function for save image param instance and and filename
def stock_image(instance, filename: str) -> str:
    """upload_image_path.

    :param instance:get instance from StockItem
    :param filename:get filename to set folder
    """
    ext = filename.split(".")[-1]
    filename = f"{uuid.uuid4()}.{ext}"
    return f"StockItem/{instance.stock_item.item_name}/{filename}"


# class categories for stock
class Category(models.Model):
    """
    Category model

    Attributes:
        name:
        description:
        created_at:
        updated_at:
        image:
    """

    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="StockItem/Categories/", null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


# class for supplier for stock
class Supplier(models.Model):
    """
    Supplier model

    Attributes:
        name:
        address:
        contact_no:
        created_at:
        updated_at:
    """

    name = models.CharField(max_length=50)
    address = models.TextField()
    contact_no = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.contact_no}"


class Network(models.Model):
    """for network detail have fields : name, ip_addr, description"""

    name = models.CharField(max_length=50)
    ip_addr = models.GenericIPAddressField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.ip_addr}"


class Manufacturer(models.Model):
    """
    Manufacturer model

    Attributes:
        name:
        description:
        created_at:
        updated_at:
    """

    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class StockItemManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=StockItem.Status.AVAILABLE)


class StockItem(models.Model):
    """
    StockItem. for store item

    Attributes:
        item_name:
        serial:
        description:
        supplier:
        quantity:
        stock_control:
        location_install:
        location_item:
        created_at:
        updated_at:
        manufacturer:
        model_no:
        part_no:
        price:
        network:
        category:
        is_deleted:
        status:
        count_text:
        objects:
        available:
    """

    class Status(models.TextChoices):
        """Status."""

        AVAILABLE = "AVAILABLE", "พร้อมใช้งาน"
        IN_USE = "IN_USE", "กำลังใช้งาน"
        UNDER_MAINTENANCE = "UNDER_MAINTENANCE", "ซ่อมบำรุง"
        DISPOSED = "DISPOSED", "จำหน่าย"
        CHECK = "CHECK", "ตรวจสอบ"
        HOLD = "HOLD", "จอง"
        ON_HAND = "ON_HAND", "เคลื่อนไหว"

    class StockControl(models.TextChoices):
        """StockControl."""

        RELAY = "RELAY", "คลังวิทยุถ่ายทอด"
        SATT = "SATT", "คลังดาวเทียม"
        FO = "FO", "คลังใยแก้วนำแสง"
        DATA = "DATA", "คลังสื่อสารข้อมูล"
        AIR = "AIR", "คลังเครื่องปรับอากาศ"

    item_name = models.CharField(max_length=50)
    serial = models.CharField(max_length=50, unique=True, null=True, blank=True)
    description = models.TextField()
    supplier = models.ForeignKey(
        Supplier, on_delete=models.CASCADE, null=True, blank=True
    )
    quantity = models.PositiveIntegerField(default=1)
    # location   = models.CharField(max_length=255, null=True, blank=True)
    stock_control = models.CharField(
        max_length=20, choices=StockControl.choices, null=True, blank=True
    )
    location_install = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="location_install",
    )
    location_item = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="location_item",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    manufacturer = models.ForeignKey(
        Manufacturer, on_delete=models.CASCADE, null=True, blank=True
    )
    model_no = models.CharField(max_length=50, null=True, blank=True)
    part_no = models.CharField(max_length=50, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    network = models.ForeignKey(
        Network, on_delete=models.CASCADE, null=True, blank=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank=True
    )
    is_deleted = models.BooleanField(default=False)
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.AVAILABLE
    )
    count_text = models.CharField(max_length=50, null=True, blank=True)

    objects = models.Manager()  # default Manager
    available = StockItemManager()  # Custom manager filter available stock_item

    def __str__(self):
        return f"{self.item_name} Serial: {self.serial} Status: {self.status} Location: {self.stock_control}"

    def get_absolute_url(self):
        return reverse("asset:stockitem_detail", kwargs={"pk": self.pk})


class StockItemImage(models.Model):
    """StockItemImage."""

    stock_item = models.ForeignKey(
        StockItem, on_delete=models.CASCADE, related_name="images"
    )
    images = models.ImageField(upload_to=stock_image)

    def __str__(self):
        return f"{self.stock_item.item_name} - {self.images.name}"


class ItemLocation(models.Model):
    """
    ItemLocation model for mapping item and location

    Attributes:
        item:
        location:
    """

    item = models.ForeignKey(StockItem, on_delete=models.CASCADE)
    location = models.ForeignKey(Department, on_delete=models.CASCADE)


class ItemOnHand(models.Model):
    """
    ItemOnHand model for tracking item on hand

    Attributes:
        item:
        user:
        created_at:
        is_done:
    """

    item = models.ForeignKey(StockItem, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_done = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.item.item_name} - {self.user.get_full_name()}"


class ItemHistory(models.Model):
    """ItemHistory."""

    item = models.ForeignKey(StockItem, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.item.item_name} - {self.user.get_full_name()}"

asset/templates/asset/stockitem_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<section>
  <div class="container">
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete this item?</p>
    <ul>
      <li>{{ item }}</li>
    </ul>
  </div>
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      <button class="btn btn-danger" type="submit">Yes</button>
      <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">No</a></a>
    </form>
  </div>
</section>
{% endblock %}

asset/templates/asset/stockitem_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tags %}
{% load tz %}

  {% block title %}{{ object.item_name }}{% endblock title %}

  {% block content %}
<div class="pagetitle">
  <h1>พัสดุ {{ object.item_name }}</h1>
  <p> หมายเลข {{ object.serial }}</p>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'asset:stockitem_home' %}">StockItem Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'asset:stockitem_list' %}">StockItem List</a></li>
      <li class="breadcrumb-item active">{{ object.item_name }}</li>
    </ol>
  </nav>
</div><!-- End Page Title -->


<section class="section">
  <div class="row">

    <div class="col-xl-12">
      <div class="card">
        <div class="card-body pt-3">
          <ul class="nav nav-tabs nav-tabs-bordered">
            <li class="nav-item">
              <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#detail">
                รายละเอียด
              </button>
            </li>
            {% if images %}
            <li class="nav-item">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#image">
                ภาพพัสดุ
              </button>
            </li>
            {% endif %}
            {% if repair %} <!-- change to repair -->
            <li class="nav-item">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#repair">
                ประวัติการซ่อมบำรุง
              </button>
            </li>
            {% endif %}
          </ul>

          <!-- start tab content -->
          <div class="tab-content pt-2">
            <div id="detail" class="tab-pane fade show active">
              <h6 class="card-title"> รายละเอียด | <span> {{ object.item_name }} - {{ object.serial }}</span></h6>
              <table class="table">
                {% comment %}<p>{{ booking }}</p>{% endcomment %}
                {% comment %}<p>{{ car_fix }}</p>{% endcomment %}
                <tr>
                  <th>ประเภท</th>
                  <td>
                    <a href="{% url 'asset:category_list' pk=object.category.pk %}">
                      {{ object.category.name }}
                    </a>
                  </td>
                </tr>

                <tr>
                  <th>ชื่อพัสดุ</th>
                  <td>{{ object.item_name }}</td>
                </tr>

                <tr>
                  <th>คลังเจ้าของพัสดุ</th>
                  <td>
                    {{ object.get_stock_control_display }}
                  </td>
                </tr>

                <tr>
                  <th>หมายเลข Serial</th>
                  <td>{{ object.serial }}</td>
                </tr>

                <tr>
                  <th>ผู้ผลิต/ยี่ห้อ</th>
                  <td>
                    <a href="{% url 'asset:manufacturer_list' pk=object.manufacturer.pk %}">
                      {{ object.manufacturer.name }}
                    </a>
                  </td>
                </tr>

                <tr>
                  <th>Model no.</th>
                  <td>{{ object.model_no }}</td>
                </tr>

                <tr>
                  <th>Part no.</th>
                  <td>{{ object.part_no|default:"-" }}</td>
                </tr>

                {% if object.location_install %}
                <tr>
                  <th>การติดตั้ง</th>
                  <td>{{ object.location_install.name }}</td>
                </tr>

                {% endif %}

                <tr>
                  <th>สถานภาพ</th>
                  <td>{{ object.get_status_display }}</td>
                </tr>

                {% if object.location_install %}
                <tr>
                  <th>สถานที่ติดตั้ง</th>
                  <td>{{ object.location_install.name }}</td>
                </tr>
                {% endif %}

              </table>



            </div><!-- end detail -->

            <!-- DONE: image tab -->
            <div id="image" class="tab-pane fade pt-3">
              <h5 class="card-title">ภาพพัสดุ | <span>{{ object.item_name }} ({{ object.serial }})</span></h5>
              <div id="gallery">
                {% for item in images %}
                {% comment %} <a class="col s12 m3" href="{{ item.images.url }}" target="_blank">
                <img height="150" width="150" src="{{ item.images.url }}" alt="">
                </a> {% endcomment %}
                <a class="col s12 m3" href="javascript:pswpInit({{forloop.counter0}})">
                  <img height="250" width="250" src="{{ item.images.url }}" alt="">
                </a>
                {% endfor %}
              </div>
              <!-- table booking list with search -->

            </div><!-- end repair -->

            <!-- FIX: repair tab -->
            <div id="repair" class="tab-pane fade pt-3">
              <h5 class="card-title">ประวัติการซ่อมบำรุง | <span>{{ object.number }}</span></h5>

              <!-- table booking list with search -->
              <table id="TableBooking" class="table table-hover datatable">
                <thead>
                  <tr>
                    <th scope="col">ภารกิจ</th>
                    <th scope="col">วันที่ขอใช้งาน</th>
                    <th scope="col">ผู้ควบคุม</th>
                    <th scope="col">ผู้อนุมัติ</th>
                    <th scope="col">สถานะ</th>
                  </tr>
                </thead>
                <tbody>
                  {% for bk in booking_list %}
                  <tr>
                    <td>
                      <a href="{% url 'car:booking-detail' pk=bk.pk %}">
                        {{ bk.mission }}
                      </a>
                    </td>
                    <td>{{ bk.requested_at|thaidate }}</td>
                    <td>{{ bk.controler }}</td>
                    <td>{{ bk.approver }}</td>
                    {% if not bk.mile_in %}
                    <td>{{ bk.approve_status }}</td>
                    {% else %}
                    <td>เสร็จสิ้น</td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>

            </div><!-- end repair -->
          </div>

        </div><!-- end tab -->


        <!-- TODO: make condition for button -->
        <div class="container float-start text-center">
          <!-- DONE: send pk to booking view -->
          {% if object.status == 'AVAILABLE' %}
          <form id="add-form" action="{% url 'cart:cart_add' object.category.pk %}" method="post">
            {% csrf_token %}
            <!-- <a href="#" class="btn btn-primary" onclick="addTest"><span class="bi bi-plus-circle"></span> Add to cart</a> -->
            <!-- input quantity increase and decreasee button -->
            <input type="hidden" name="quantity" id="quantity-{{ object.category.pk }}" value="1" class="form-control mb-2">
            {% if ct.pk in request.session.cart %}
            <input type="hidden" name="override" id="override-{{ object.category.pk }}" value="False">
            {% else %}
            <input type="hidden" name="override" id="override-{{ object.category.pk }}" value="True">
            {% endif %}
            <input type="hidden" name"stock" value="{{ object.location.pk }}">
            <!-- <a href="#" class="btn btn-primary"><span class="bi bi-plus-circle"></span> Add to cart</a> -->
            <a href="{% url 'asset:stockitem_list' %}" class="btn btn-lg btn-secondary">ย้อนกลับ</a>
            <button type="submit" class="btn btn-lg btn-primary">ขอเบิก</button>
            <!-- <a href="#" class="btn btn-lg btn-warning">ขอเบิก</a> -->
            {% endif %}
            {% if perms.asset.change_stockitem or request.user.profile.department == object.location %}
            {% if object.status == 'AVAILABLE'  %}
            <a href="{% url 'asset:stockitem_update' pk=object.pk %}" class="btn btn-lg btn-info">แก้ไข</a>
            {% else %}
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-lg btn-secondary">ย้อนกลับ</a></a>
            {% endif %}
            {% endif %}
        </div>
        <br />

        <br />
      </div>

    </div><!-- end tab content -->

  </div>

</section>
{% include 'components/photoswipe.html' %}
{% endblock content %}

asset/templates/asset/stockitem_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load tags %}
{% load tz %}

  {% block title %}StockItem Stock{% endblock title %}

  {% block content %}

  <div class="pagetitle">
    <h1>รายการพัสดุ หน่วย {{ request.user.profile.department.name }}</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'asset:stockitem_home' %}">StockItem Home</a></li>
        <li class="breadcrumb-item active">รายการพัสดุ</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section profile">
    <div class="row">

      <div class="col-xl-12">

        <!-- Recent Job -->
        <div class="col-12">
          <div class="card recent-sales overflow-auto">

            <div class="card-body">
              <h5 class="card-title">{{ title }} 
                <span>| รายการพัสดุ</span>
                  
                {#% if perms.asset.add_stockitem %#}
                <a href="{% url 'asset:stockitem_create' %}" 
                  class="btn btn-success"
                  style="float: right;">
                  <i class="bi bi-plus"></i>
                  เพิ่มพัสดุ {{ request.user.profile.department.name }}
                </a>
                {#% endif %#}
              </h5>

              <br>

              <table class="table table-hover" id="dataTable">
                <thead>
                  <tr>
                    <th scope="col">ประเภทพัสดุ</th>
                    <th scope="col">serial</th>
                    <th scope="col">ชื่อพัสดุ</th>
                    <th scope="col">ยี่ห้อ</th>
                    <th scope="col">สถานะ</th>
                    <th scope="col">การติดตั้ง</th>
                    <th scope="col">Network</th>
                    <th scope="col">...</th>
                  </tr>
                </thead>
                <tbody>
                  {% for object in object_list %}
                  <tr>
                    <td>
                      <a href="{% url 'asset:category_list' pk=object.category.pk %}">
                        {{ object.category.name }}
                      </a>
                    </td>
                    <td>
                      <a href="{% url 'asset:stockitem_detail' pk=object.pk %}">
                        {{ object.serial }}
                      </a>
                    </td>
                    <td>
                      {{ object.item_name }}
                    </td>
                    <td>
                      {% if object.manufacturer %}
                      <a href="{% url 'asset:manufacturer_list' pk=object.manufacturer.pk %}">
                        {{ object.manufacturer.name }}
                      </a>
                      {% endif %}
                    </td>
                    {% if object.get_status_display == 'พร้อมใช้งาน' %}
                    <td><span><i class="bi bi-check-circle-fill" style="color: green"></i></span> {{ object.get_status_display }}</td>
                    {% else %}
                    <td>{{ object.get_status_display }}</td>
                    {% endif %}
                    <td>{% if object.location_install %}
                      {{ object.location_install.name }}
                      {% else %}
                      {{ object.get_stock_control_display }}
                      {% endif %}</td>
                    <td>
                      {% if object.network %}
                      <a href="{% url 'asset:network_list' pk=object.network.pk %}">
                        {{ object.network.ip_addr|default:"-" }}
                      </a>
                      {% else %}
                      -
                      {% endif %}
                    </td>
                    <td>
                      <a href="{% url 'asset:stockitem_detail' pk=object.pk %}" class="btn btn-primary btn-sm"><i class="bi bi-info-circle"></i></a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>

            </div>

          </div>
        </div><!-- End Announce List -->
        {% comment %}{% if perms.announce.view_announce %}Permission Grant{% endif %}{% endcomment %}

      </div>
    </div>
  </section>

  <script>
  $(document).ready(() => {
    $("#dataTable").DataTable({
      "fnDrawCallback" : function(oSettings) {
        if (oSettings._iDisplayLength > oSettings.fnRecordsDisplay()) {
          $(oSettings.nTableWrapper).find('.dataTables_paginate').hide();
        } else {
          $(oSettings.nTableWrapper).find('.dataTables_paginate').show();
        }
      },
      "lengthMenu": [ [10, 25, 50, -1], [10, 25, 50, "All"] ],
      order: [[ 4, "asc" ]]
    });
  });
  </script>
  {% endblock content %}